# Generated by Django 5.0.4 on 2024-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
